<?php
session_start(); //needed to show error messages on the form

$error = $_SESSION['error_v3'] ?? '';
unset($_SESSION['error_v3']); //clear error so it doesnt show again on refresh

$recaptchaSiteKey = '6LfTC4AtAAAAAIzkM_w16VefpfhMHUFjTZ3pfHFv'; //shouldnt be pushed into the repo but for simplicity I will
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- loads google recaptcha v3 (needs ?render= site key, not the v2 script) -->
    <script src="https://www.google.com/recaptcha/api.js?render=<?php echo htmlspecialchars($recaptchaSiteKey, ENT_QUOTES, 'UTF-8'); ?>"></script>
    <title>Create Account - reCAPTCHA v3</title>
</head>
<body>
    <h1>Alice's Shop - Registry</h1>

    <?php if ($error !== ''): ?>
        <p><?php echo htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></p> <?php //escape output to prevent xss ?>
    <?php endif; ?>

    <form id="register-form-v3" action="process_v3.php" method="post">
        <p>
            <label>Username<br>
                <input type="text" name="username" required maxlength="50"> <!-- limit input size to prevent abuse -->
            </label>
        </p>
        <p>
            <label>Password<br>
                <input type="password" name="password" required minlength="10" maxlength="128"> <!-- copied input field parameters from figure-2.2 again to prevent XSS attacks -->
            </label>
        </p>
        <p>Password must be at least 10 characters and include uppercase, lowercase, and a number.</p>
        <p>
            <label>Confirm Password<br>
                <input type="password" name="confirm_password" required minlength="10" maxlength="128"> <!-- must match password field -->
            </label>
        </p>

        <input type="hidden" name="g-recaptcha-response" id="g-recaptcha-response"> <!-- v3 token goes here before submit -->

        <button type="submit">Register</button>
        <button type="reset">Reset</button> <!-- clears all form fields back to default -->
    </form>

    <script>
        // v3 token is generated by the execute() function and sent to process_v3.php by pressing submit
        document.getElementById('register-form-v3').addEventListener('submit', function (event) {
            event.preventDefault();

            grecaptcha.ready(function () {
                grecaptcha.execute('<?php echo htmlspecialchars($recaptchaSiteKey, ENT_QUOTES, 'UTF-8'); ?>', { action: 'register' })
                    .then(function (token) {
                        document.getElementById('g-recaptcha-response').value = token;
                        event.target.submit();
                    });
            });
        });
    </script>
</body>
</html>
